gangs:
  # How many mobs must have attacked a player to be considered a gang?
  size: 2
messages:
  # Should the default message in messages.yml be sent if we can't figure out a death reason?
  use-default: true

discord:
  enabled: true
  messages:
    player:
      enabled: true
      # Format channels as "<guild-id>:<channel-id>"
      channels: []
    mob:
      enabled: true
      channels: []
    entity:
      enabled: true
      channels: []
    natural:
      enabled: true
      channels: []